#!/bin/bash
# 🚀 PRÓXIMOS PASOS PARA PONER EN VIVO

echo "================================================"
echo "✨ Dashboard SaaS - Próximos Pasos"
echo "================================================"
echo ""

# Verificar Docker
echo "🔍 Verificando Docker..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker no está instalado"
    echo "   Descargar: https://www.docker.com/products/docker-desktop"
    exit 1
fi

echo "✅ Docker disponible"
echo ""

# Opción 1: Docker
echo "================================================"
echo "OPCIÓN 1: Iniciar con Docker (Recomendado)"
echo "================================================"
echo ""
echo "Ejecuta:"
echo "  docker-compose up -d"
echo ""
echo "Luego accede a:"
echo "  Frontend: http://localhost:3001"
echo "  API:      http://localhost:3000/api/health"
echo ""

# Opción 2: Local
echo "================================================"
echo "OPCIÓN 2: Desarrollo Local"
echo "================================================"
echo ""
echo "Instala Node.js 20+ desde: https://nodejs.org"
echo ""
echo "Luego en 3 terminales:"
echo ""
echo "Terminal 1 - Backend:"
echo "  cd backend"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "Terminal 2 - Frontend:"
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "Terminal 3 - PostgreSQL (si no tienes):"
echo "  docker run -d -e POSTGRES_PASSWORD=secure_password -e POSTGRES_DB=chatbot_saas -p 5432:5432 postgres:15-alpine"
echo ""

# Opción 3: Deploy
echo "================================================"
echo "OPCIÓN 3: Deploy en Producción"
echo "================================================"
echo ""
echo "Leer: DEPLOY_RENDER.md"
echo "  1. Push a GitHub"
echo "  2. Crear servicios en Render.com"
echo "  3. Tu SaaS está vivo! 🎉"
echo ""

# Guía rápida
echo "================================================"
echo "PRIMEROS PASOS EN EL DASHBOARD"
echo "================================================"
echo ""
echo "1. Registrar: http://localhost:3001/register"
echo "   - Email: tu@email.com"
echo "   - Password: 123456"
echo "   - Nombre: Tu Nombre"
echo "   - Empresa: Tu Tienda"
echo ""
echo "2. Login: http://localhost:3001/login"
echo ""
echo "3. Configurar:"
echo "   - Configurar Tienda: Nombre, descripción, ubicación"
echo "   - Contexto IA: Describe tu negocio (para el bot)"
echo ""
echo "4. Catálogo:"
echo "   - Productos: Agregar productos con precios"
echo "   - Servicios: Agregar servicios (próximamente)"
echo "   - Horarios: Configurar disponibilidad"
echo ""
echo "5. Pagos:"
echo "   - Agregar medios de pago (alias, cuentas bancarias)"
echo ""

# Ayuda
echo "================================================"
echo "🆘 SOLUCIÓN DE PROBLEMAS"
echo "================================================"
echo ""
echo "¿No puedo acceder a localhost:3001?"
echo "  → Esperar 30 segundos para que se compile"
echo "  → Ver logs: docker-compose logs -f frontend"
echo ""
echo "¿Error de conexión a base de datos?"
echo "  → PostgreSQL necesita tiempo para iniciar"
echo "  → Ver logs: docker-compose logs postgres"
echo "  → Reintentar después de 30 segundos"
echo ""
echo "¿¿Necesito ver código?"
echo "  → Backend API: backend/src/"
echo "  → Frontend UI: frontend/src/"
echo "  → Database: database/schema.sql"
echo ""
echo "¿Documentación completa?"
echo "  → README.md (general)"
echo "  → QUICKSTART.md (inicio rápido)"
echo "  → DEPLOY_RENDER.md (para producción)"
echo "  → IMPLEMENTACION_COMPLETA.md (resumen)"
echo ""

echo "================================================"
echo "🎯 ¡Listos para empezar!"
echo "================================================"
echo ""
